### ISSUE TITLE
Schedule has changed, I think...

### ISSUE THREAD

**Issue by Shaftoe62** [richardwestenra/rdr2-free-roam-event-schedule#1]
Hello Richard,

Like your schedule but I think the Free Roam Schedule has changed.

I have noted the following changes so far:

UTC time: 
4:30 - Lake Fishing Challenge
11:15 - Long Arm Kills Challenge

I'm not for a full 100% sure of this but I will continue to make notes.

**Comment by richardwestenra** [comment]
Ok cool, thanks for the heads-up! I'll change those soon.
