### ISSUE TITLE
Last two days have been off (naturalist schedule again?)

### ISSUE THREAD

**Issue by ruffin--** [richardwestenra/rdr2-free-roam-event-schedule#16]
Since Tuesday update, at least the trader event at 2:52pm Eastern hasn't happened.

I think we're back on the Naturalist highlight schedule. Do you have the old one you mentioned having up until 27 Jan somewhere to see if it's the same again?

**Comment by ruffin--** [comment]
Well, did find the [old naturalist schedule](https://github.com/richardwestenra/rdr2-free-roam-event-schedule/commit/49e336610f53e76352ec4b611423d44678152551#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051), but haven't compared yet:

```
          ['00:22','Day of Reckoning (Bounty Hunter)'], 
          ['01:52','Day of Reckoning (Bounty Hunter)'],
          ['03:22','Wild Animal Tagging (Naturalist)'],
          ['04:52','Protect Legendary Animal (Naturalist)'],
          ['06:22','Manhunt (Bounty Hunter)'],
          ['07:52','Wild Animal Tagging (Naturalist)'],
          ['09:22','Protect Legendary Animal (Naturalist)'],
          ['10:52','Trade Route (Trader)'],
          ['12:22','Wild Animal Tagging (Naturalist)'],
          ['13:52','Protect Legendary Animal (Naturalist)'],
          ['15:22','Salvage (Collector)'],
          ['16:52','Wild Animal Tagging (Naturalist)'],
          ['18:22','Protect Legendary Animal (Naturalist)'],
          ['19:52','Condor Egg (Collector)'],
          ['21:22','Wild Animal Tagging (Naturalist)'],
          ['22:52','Protect Legendary Animal (Naturalist)']
```

Would jibe with what I saw at 2:52pm Eastern (19:52 UTC) though... I didn't receive an invite to anything, and I'm not a Collector.

---

EDIT: Yep. Just did the Protect Legendary Animal event at 1:22pm Eastern.

**Comment by richardwestenra** [comment]
I just updated it, thanks for the heads-up!
