### ISSUE TITLE
Not ever accurate.

### ISSUE THREAD

**Issue by cowboyrichards** [richardwestenra/rdr2-free-roam-event-schedule#18]
I experience numerous trade routes a day, and salvages as well. this is an ineffecient guide

**Comment by richardwestenra** [comment]
Hi @cowboyrichards, sorry we got a few updates from Rockstar this year that meant the schedule kept changing, and I also went through a pretty turbulent time in my personal/work life so I wasn't able to keep it updated frequently for a few months there.

However the schedule is now pulling live event data from https://api.rdo.gg/ as its source, so it should stay much more up to date. Thanks!
