### ISSUE TITLE
New Role Schedule

### ISSUE THREAD

**Issue by viniferreira** [richardwestenra/rdr2-free-roam-event-schedule#5]
Hi Richard,

Thanks for your schedule, but I think Role’s schedule has changed.

I’ve noticed the following changes so far:

UTC Time:
15:22 - Manhunt (Bounty Hunter)
19:52 - Condor Egg (Collector)

**Comment by alonsofedz** [comment]
UTC Time:
03:22 - Protect the Legendary (Naturalist)
16:22 - Protect the Legendary (Naturalist)

**Comment by UniSpaceX** [comment]
UTC Time:
06:22 - Salvage (Collector)
10:52 - Trade Route (Trader)

**Comment by notaskunk** [comment]
UTC Time:
00:12 - Master Archer
00:22 - Wild Animal Tagging (Naturalist)

**Comment by richardwestenra** [comment]
Thanks all! I have updated the timetable as of 7fbf68ea9045bce1bc77053aaaa5db363f93ca3e using [Trinerity's data from Reddit](https://www.reddit.com/r/RedDeadOnline/comments/i0n492/new_free_roam_events_schedule/) which seems fairly consistent with your reported event times. so this should be resolved now. Let me know if you still see any issues with the new data :)
