### ISSUE TITLE
Non-Role Free Roam Events slightly off since Naturalist DLC

### ISSUE THREAD

**Issue by notaskunk** [richardwestenra/rdr2-free-roam-event-schedule#6]
Hi!

Just a heads up, from what I've noticed, Master Archer takes place at 2:12 AM CET — or 12:12 AM UTC — instead of 2:00 AM CET now.

It doesn't seem like the actual schedule is that different, but it seems as though some non-role events may now take place twelve minutes after their pre-Naturalist DLC time, for whatever reason.

**Comment by viniferreira** [comment]
I think the event times that you used as a source for the last update is wrong.

**Comment by richardwestenra** [comment]
Hopefully this is now resolved, as we have updated the schedule a few times in the last few weeks.
