### ISSUE TITLE
schedule is incorrect

### ISSUE THREAD

**Issue by githb123** [richardwestenra/rdr2-free-roam-event-schedule#7]
The schedule seems to have been updated again. I was getting completely different events today. They weren't shifted but just randomly different.

**Comment by AdamNortonUK** [comment]
I believe when they added the Wildlife Photography event, for the first couple of a weeks they set it as every other event, the events are now back to normal with Wildlife Photography not being every other event. I am nearly done with a new list so that the site can be updated.

**Comment by richardwestenra** [comment]
Hopefully this is now resolved, as we have updated the schedule a few times lately.
